apiVersion: apps/v1
kind: Deployment
metadata:
 name: addydep
 labels:
   run: addy
spec:
#specify the number of replicas
 replicas: 2
 selector:
#the lable specified in the selector should match the label 
  matchLabels:
   run: addy
 template:
#in template the lable should match to the metadata of the deployment
  metadata:
   labels:
    run: addy
  spec:
   containers:
#you can specify the name of the image
   - image: nginx
#you can give the name for the container
     name: addy