apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: tester
spec:
  containers:
  - image: busybox:stable-musl
    name: live-cont
    args:
    - /bin/bash
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3 
