apiVersion: v1
kind: Pod
metadata:
  labels:
    run: addy
  name: addy
spec:
  containers:
  - image: nginx
    name: first
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
    
  - image: debian
    name: second
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh" , "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done
  volumes:
  - name: html
    emptyDir: {}