apiVersion: apps/v1
kind: Deployment
metadata:
 name: addydep
 labels:
   app: addy
spec:
#specify the number of replicas
 replicas: 2
 selector:
#the lable specified in the selector should match the label
  matchLabels:
   app: addy
 template:
#in template the lable should match to the metadata of the deployment
  metadata:
   labels:
    app: addy
  spec:
   containers:
#you can specify the name of the image
   - image: nginx
#you can give the name for the container
     name: addy
#to make sure if all the pods should be scheduled to a particular node we have to add nodeselector field below the 
#container field
   nodeSelector:
#we should enter the label key and value so that the pod will be scheduled to the desired node
     disktype: ssd