apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: addydep
 labels:
   run: addy
spec:
 replicas: 2
 selector:
  matchLabels:
   run: addy
 template:
  metadata:
   labels:
    run: addy
  spec:
   containers:
   - image: nginx
     name: addy